import React, { createContext, useContext } from 'react';

export type PropKind = 'number' | 'color' | 'text' | 'list';

// list 型条目的子字段
export interface ListField {
  key: string;           // 条目对象中的字段名
  label: string;         // 面板显示名
  placeholder?: string;
  multiline?: boolean;   // 多行输入(说明文本)
  default?: string;
  kind?: 'text' | 'color'; // 输入类型，color 时显示颜色选择面板(默认 text)
  sizeKey?: string;      // 文本二级属性：该文本对应的字号属性 key（一级隐藏）
  colorKey?: string;     // 文本二级属性：该文本对应的颜色属性 key（一级隐藏）
  note?: string;         // 一级提示，如“连接线/亮点颜色跟随此文本”
}

export interface PropDef {
  key: string;
  label: string;
  kind: PropKind;
  default: number | string;
  min?: number;
  max?: number;
  step?: number;
  unit?: string;
  options?: { label: string; value: string }[];
  listFields?: ListField[];
  /** Reviewed list-item keys that Agents may edit when style/animation keys share the same list prop. */
  agentEditableItemFields?: string[];
  // 文本二级属性（仅 kind:'text'）：点击 T 图标展开的字号/颜色属性 key
  sizeKey?: string;
  colorKey?: string;
  // 文本二级属性（仅 kind:'text'）：重点词{{}}颜色属性 key（一级隐藏）
  hlColorKey?: string;
  // 一级提示：边框/线段颜色跟随该文本属性修改
  note?: string;
}
export type ConfigState = Record<string, number | string>;

export const mkNum = (key: string, label: string, def: number, min: number, max: number, step = 1, unit = 'px'): PropDef =>
  ({ key, label, kind: 'number', default: def, min, max, step, unit });
export const mkColor = (key: string, label: string, def: string): PropDef =>
  ({ key, label, kind: 'color', default: def });
// 文本：一级只显示输入框 + T 图标，字号/颜色为二级属性（sizeKey/colorKey），重点词{{}}颜色为三级二级属性（hlColorKey）
export const mkText = (key: string, label: string, def: string, sizeKey: string, colorKey: string, note?: string, hlColorKey?: string): PropDef =>
  ({ key, label, kind: 'text', default: def, sizeKey, colorKey, note, hlColorKey });
// list：数据条目列表，default 为 JSON 字符串(数组)
export const mkList = (
  key: string,
  label: string,
  def: string,
  listFields: ListField[],
  agentEditableItemFields?: string[],
): PropDef => ({ key, label, kind: 'list', default: def, listFields, agentEditableItemFields });

// 通用文本控件
const C_SIZE = 'titleSize', C_COLOR = 'titleColor', C_SUBSIZE = 'subSize',
  C_SUBCOLOR = 'subColor', C_ACCENT = 'accentColor', C_LINE = 'lineColor';

/**
 * 各组件可编辑属性定义。默认值严格遵循规范文档的色彩与字号。
 * 文本属性通过 sizeKey/colorKey 指向字号/颜色二级属性，一级面板只显示输入框 + T 图标。
 */
export const CONFIGS: Record<string, PropDef[]> = {
  // ================= 第一大类 纯文字+细线条 =================
  't1-01': [
    mkText('tagText', '顶部标签文案', 'LOOP', 'tagSize', 'subColor'),
    mkText('enText', '英文标签文案', 'TECHNOLOGY ANALYSIS', 'enSize', 'accentColor'),
    mkText('titleText', '主标题文案', 'AI智能算法迭代升级', 'titleSize', 'titleColor'),
    mkText('subText', '副标题文案', '基于深度学习的全新算力优化方案', 'subSize', 'subColor'),
    mkNum(C_SIZE, '主标题字号', 61, 30, 96),
    mkColor(C_COLOR, '主标题颜色', '#FFFFFF'),
    mkNum(C_SUBSIZE, '副标题字号', 28, 20, 70),
    mkColor(C_SUBCOLOR, '副标题颜色', '#E6E6E6'),
    mkColor(C_ACCENT, '英文标签色', '#4CC9F0'),
    mkNum('tagSize', '顶部标签字号', 26, 16, 60),
    mkNum('enSize', '英文标签字号', 30, 16, 60),
  mkNum('posX', '左位置X', 1220, 0, 1920, 1, 'px'),
    mkNum('posY', '顶部位置Y', 160, 0, 1080, 1, 'px'),
    mkNum('scale', '整体缩放', 100, 20, 200, 1, '%'),
  ],
  't1-02': [
    mkText('quoteText', '引用文案', '技术迭代的核心，是效率与体验的双向突破', 'subSize', 'titleColor'),
    mkText('noteText', '注释文案', '行业核心共识 · 2026技术发展准则', 'titleSize', 'noteColor'),
    mkColor(C_LINE, '竖线颜色', '#4CC9F0'),
    mkNum(C_SUBSIZE, '引用文字号', 46, 24, 70),
    mkColor(C_COLOR, '引用文字颜色', '#FFFFFF'),
    mkNum(C_SIZE, '注释字号', 25, 18, 60),
    mkColor('noteColor', '注释文字颜色', '#E6E6E6'),
  mkNum('posX', '左位置X', 140, 0, 1920, 1, 'px'),
    mkNum('posY', '顶部位置Y', 220, 0, 1080, 1, 'px'),
    mkNum('scale', '整体缩放', 100, 20, 200, 1, '%'),
  ],
  't1-03': [
    mkText('noteText', '注解文案', '核心技术亮点', 'subSize', 'subColor'),
    mkText('titleText', '主标题文案', '全域智能感知系统', 'titleSize', 'titleColor'),
    mkNum(C_SUBSIZE, '注解字号', 30, 18, 60),
    mkColor(C_SUBCOLOR, '注解颜色', '#E6E6E6'),
    mkNum(C_SIZE, '主标题字号', 58, 40, 120),
    mkColor(C_COLOR, '主标题颜色', '#FFFFFF'),
  mkNum('posX', '左位置X', 130, 0, 1920, 1, 'px'),
    mkNum('posY', '顶部位置Y', 180, 0, 1080, 1, 'px'),
    mkNum('scale', '整体缩放', 100, 20, 200, 1, '%'),
  ],
  't1-04': [
    mkText('tagText', '小标题文案', 'TECH PROGRESS', 'subSize', 'accentColor'),
    mkText('titleText', '主标题文案', '算力效能全面升级', 'titleSize', 'titleColor'),
    mkText('descText', '副标题文案', '突破传统算力瓶颈，实现全域效率提升', 'descSize', 'descColor'),
    mkNum(C_SUBSIZE, '小标题字号', 25, 20, 64),
    mkColor(C_ACCENT, '小标题色', '#4CC9F0'),
    mkNum(C_SIZE, '主标题字号', 60, 32, 110),
    mkColor(C_COLOR, '主标题颜色', '#FFFFFF'),
    mkNum('descSize', '副标题字号', 25, 20, 70),
    mkColor('descColor', '副标题颜色', '#E6E6E6'),
  mkNum('posX', '左位置X', 130, 0, 1920, 1, 'px'),
    mkNum('posY', '顶部位置Y', 180, 0, 1080, 1, 'px'),
    mkNum('scale', '整体缩放', 100, 20, 200, 1, '%'),
  ],
  't1-05': [
    mkText('titleText', '主标题文案', '智能化场景落地应用', 'titleSize', 'titleColor'),
    mkText('descText', '副标题文案', '多场景适配 · 高兼容 · 低损耗运行机制', 'subSize', 'descColor'),
    mkColor(C_LINE, '线条颜色', '#4CC9F0'),
    mkNum(C_SIZE, '主标题字号', 58, 40, 130),
    mkColor(C_COLOR, '主标题颜色', '#FFFFFF'),
    mkNum(C_SUBSIZE, '副标题字号', 26, 16, 70),
    mkColor('descColor', '副标题颜色', '#E6E6E6'),
  mkNum('posX', '左位置X', 130, 0, 1920, 1, 'px'),
    mkNum('posY', '顶部位置Y', 200, 0, 1080, 1, 'px'),
    mkNum('scale', '整体缩放', 100, 20, 200, 1, '%'),
  ],
  't1-06': [
    mkText('enText', '英文标签文案', 'SUMMARY', 'subSize', 'accentColor'),
    mkText('titleText', '主标题文案', '技术体系整体总结', 'titleSize', 'titleColor'),
    mkText('descText', '副标题文案', '完成全链路技术闭环，实现高效稳定运行', 'descSize', 'descColor'),
    mkColor(C_LINE, '线条颜色', '#4CC9F0'),
    mkNum(C_SUBSIZE, '英文标签字号', 20, 18, 60),
    mkColor(C_ACCENT, '英文标签色', '#4CC9F0'),
    mkNum(C_SIZE, '主标题字号', 59, 40, 130),
    mkColor('titleColor', '主标题颜色', '#FFFFFF'),
    mkNum('descSize', '副标题字号', 24, 20, 70),
    mkColor('descColor', '副标题颜色', '#E6E6E6'),
  mkNum('posX', '左位置X', 130, 0, 1920, 1, 'px'),
    mkNum('posY', '顶部位置Y', 200, 0, 1080, 1, 'px'),
    mkNum('scale', '整体缩放', 100, 20, 200, 1, '%'),
  ],
  't1-07': [
    mkText('kickerText', '顶部文字文案', 'DATA DRIVEN', 'kickerSize', 'kickerColor'),
    mkText('topText', '主标题文案', '数据驱动智能升级', 'titleSize', 'titleColor'),
    mkText('descText', '说明文案', '以数据为核心，重构智能运行逻辑', 'descSize', 'descColor'),
    mkNum(C_SIZE, '主标题字号', 54, 32, 112),
    mkColor(C_COLOR, '主标题颜色', '#FFFFFF'),
    mkNum('kickerSize', '顶部文字字号', 34, 18, 110),
    mkColor('kickerColor', '顶部文字颜色', 'rgba(255,255,255,0.28)'),
    mkNum('descSize', '说明字号', 26, 18, 70),
    mkColor('descColor', '说明颜色', '#E6E6E6'),
  mkNum('posX', '左位置X', 130, 0, 1920, 1, 'px'),
    mkNum('posY', '顶部位置Y', 200, 0, 1080, 1, 'px'),
    mkNum('scale', '整体缩放', 100, 20, 200, 1, '%'),
  ],
  't1-08': [
    mkText('tagText', '锚点标签文案', 'CORE LOGIC', 'subSize', 'accentColor'),
    mkText('titleText', '主标题文案', '核心运行逻辑解析', 'titleSize', 'titleColor'),
    mkText('bodyText', '正文文案', '依托{{自适应算法}}引擎，系统可实时调整运行策略，规避{{无效算力消耗}}，实现高效运转。', 'bodySize', 'bodyColor', undefined, 'hlColor'),
    mkColor('hlColor', '重点文本颜色', '#4CC9F0'),
    mkNum(C_SUBSIZE, '锚点标签字号', 34, 18, 60),
    mkColor(C_ACCENT, '锚点标签色', '#C77DFF'),
    mkNum(C_SIZE, '主标题字号', 58, 40, 130),
    mkColor('titleColor', '主标题颜色', '#FFFFFF'),
    mkNum('bodySize', '正文字号', 42, 22, 70),
    mkColor('bodyColor', '正文颜色', '#E6E6E6'),
  mkNum('posX', '左位置X', 130, 0, 1920, 1, 'px'),
    mkNum('posY', '顶部位置Y', 180, 0, 1080, 1, 'px'),
    mkNum('scale', '整体缩放', 100, 20, 200, 1, '%'),
  ],
  't1-09': [
    mkText('bodyText', '主文本文案', '全链路智能化改造，实现降本增效核心目标', 'titleSize', 'titleColor'),
    mkText('noteText', '注释文案', '数据统计周期：2026全年', 'subSize', 'accentColor'),
    mkNum(C_SIZE, '主文本字号', 50, 26, 80),
    mkColor(C_COLOR, '主文本颜色', '#FFFFFF'),
    mkNum(C_SUBSIZE, '注释字号', 32, 16, 56),
    mkColor(C_ACCENT, '注释颜色', '#4CC9F0'),
  mkNum('posX', '左位置X', 130, 0, 1920, 1, 'px'),
    mkNum('posY', '顶部位置Y', 300, 0, 1080, 1, 'px'),
    mkNum('scale', '整体缩放', 100, 20, 200, 1, '%'),
  ],
  // ================= 第二大类 卡片 =================
  't2-01': [
    mkText('contentText', '卡片内容文案', '核心技术突破，实现行业领先层级效能', 'titleSize', 'titleColor'),
    mkColor('borderStart', '渐变边框起点', '#4CC9F0'),
    mkColor('borderEnd', '渐变边框终点', '#C77DFF'),
    mkNum(C_SIZE, '正文字号', 52, 28, 80),
    mkColor(C_COLOR, '文字颜色', '#FFFFFF'),
  mkNum('posX', '左位置X', 130, 0, 1920, 1, 'px'),
    mkNum('posY', '顶部位置Y', 240, 0, 1080, 1, 'px'),
    mkNum('scale', '整体缩放', 100, 20, 200, 1, '%'),
  ],
  't2-02': [
    mkText('tagText', '标签文案', 'CORE ACHIEVEMENT', 'subSize', 'accentColor'),
    mkText('titleText', '主标题文案', '核心技术成果落地', 'titleSize', 'titleColor'),
    mkColor(C_LINE, '边框颜色', '#4CC9F0'),
    mkNum(C_SUBSIZE, '标签字号', 36, 18, 60),
    mkColor(C_ACCENT, '标签色', '#4CC9F0'),
    mkNum(C_SIZE, '主标题字号', 50, 26, 92),
    mkColor('titleColor', '主标题颜色', '#FFFFFF'),
  mkNum('posX', '左位置X', 130, 0, 1920, 1, 'px'),
    mkNum('posY', '顶部位置Y', 220, 0, 1080, 1, 'px'),
    mkNum('scale', '整体缩放', 100, 20, 200, 1, '%'),
  ],
  't2-03': [
    mkText('titleText', '标题文案', '核心优势亮点', 'titleSize', 'titleColor'),
    mkText('descText', '说明文案', '低功耗、高效率、高兼容的一体化运行体系', 'subSize', 'descColor'),
    mkColor(C_ACCENT, '底纹色', 'rgba(76,201,240,0.08)'),
    mkNum(C_SIZE, '标题字号', 54, 30, 100),
    mkColor(C_COLOR, '标题颜色', '#FFFFFF'),
    mkNum(C_SUBSIZE, '说明字号', 40, 20, 70),
    mkColor('descColor', '说明颜色', '#E6E6E6'),
  mkNum('posX', '左位置X', 130, 0, 1920, 1, 'px'),
    mkNum('posY', '顶部位置Y', 240, 0, 1080, 1, 'px'),
    mkNum('scale', '整体缩放', 100, 20, 200, 1, '%'),
  ],
  // ================= 第三大类 数据 =================
  't3-01': [
    mkText('noteText', '顶部说明文案', '整体运算效率', 'subSize', 'noteColor'),
    mkText('unitText', '单位文案', 'FPS', 'unitSize', 'accentColor', '外框边框颜色跟随此文本'),
    mkText('descText', '底部说明文案', '超高帧率稳定运行，无卡顿延迟', 'descSize', 'descColor'),
    mkNum('value', '数字数值', 120, 1, 9999, 1, ''),
    mkNum(C_SIZE, '数字字号', 200, 90, 320, 4),
    mkColor(C_COLOR, '数字颜色', '#FFFFFF'),
    mkNum('unitSize', '单位字号', 80, 40, 130),
    mkColor(C_ACCENT, '单位颜色', '#4CC9F0'),
    mkNum(C_SUBSIZE, '说明小字号', 36, 18, 60),
    mkColor('noteColor', '顶部说明颜色', '#E6E6E6'),
    mkNum('descSize', '底部说明字号', 38, 22, 70),
    mkColor('descColor', '底部说明颜色', '#E6E6E6'),
  mkNum('posX', '左位置X', 130, 0, 1920, 1, 'px'),
    mkNum('posY', '顶部位置Y', 200, 0, 1080, 1, 'px'),
    mkNum('scale', '整体缩放', 70, 20, 200, 1, '%'),
  ],
  't3-02': [
    mkText('tagText', '标签文案', '算力提升', 'subSize', 'accentColor', '外框边框颜色跟随此文本'),
    mkText('unitText', '单位文案', '%', 'unitSize', 'accentColor'),
    mkText('descText', '说明文案', '核心指标对比基准', 'descSize', 'descColor'),
    mkNum('value', '数值', 58, 1, 9999, 1, ''),
    mkNum(C_SUBSIZE, '标签字号', 48, 24, 80),
    mkColor(C_ACCENT, '标签色', '#4CC9F0'),
    mkNum(C_SIZE, '数值字号', 180, 80, 300, 4),
    mkColor('titleColor', '数值颜色', '#FFFFFF'),
    mkNum('unitSize', '单位字号', 64, 30, 110),
    mkNum('descSize', '说明字号', 36, 22, 70),
    mkColor('descColor', '说明颜色', '#E6E6E6'),
  mkNum('posX', '左位置X', 130, 0, 1920, 1, 'px'),
    mkNum('posY', '顶部位置Y', 240, 0, 1080, 1, 'px'),
    mkNum('scale', '整体缩放', 100, 20, 200, 1, '%'),
  ],
  't3-03': [
    mkText('labelL', '左栏标签文案', '优化前', 'labelSize', 'accentColor'),
    mkText('labelR', '右栏标签文案', '优化后', 'labelSize', 'accent2'),
    mkText('descL', '左栏说明文案', '基础算力水准', 'descSize', 'descColor'),
    mkText('descR', '右栏说明文案', '全新算力水准', 'descSize', 'descColor'),
    mkNum('valueL', '左栏数值', 45, 1, 200, 1, ''),
    mkNum('valueR', '右栏数值', 92, 1, 200, 1, ''),
    mkColor(C_ACCENT, '左栏标签色', '#4CC9F0'),
    mkColor('accent2', '右栏标签色', '#F72585'),
    mkNum('labelSize', '标签字号', 40, 20, 70),
    mkNum(C_SIZE, '数值字号', 160, 70, 260, 4),
    mkColor(C_COLOR, '数值颜色', '#FFFFFF'),
    mkNum('descSize', '说明字号', 34, 20, 70),
    mkColor('descColor', '说明颜色', '#E6E6E6'),
  mkNum('posX', '左位置X', 130, 0, 1920, 1, 'px'),
    mkNum('posY', '顶部位置Y', 240, 0, 1080, 1, 'px'),
    mkNum('scale', '整体缩放', 100, 20, 200, 1, '%'),
  ],
  't3-04': [
    mkText('titleText', '总标题文案', '核心参数指标', 'titleSize', 'titleColor'),
    mkList('rows', '数据条目', JSON.stringify([
      { k: '延迟', v: '8ms', d: '超低运行延迟', at: 0 },
      { k: '功耗', v: '12W', d: '低功耗运行', at: 0.5 },
      { k: '准确率', v: '99.6%', d: '超高识别精度', at: 1 },
    ]), [
      { key: 'k', label: '名称', placeholder: '名称', default: '参数', sizeKey: 'subSize', colorKey: 'accentColor' },
      { key: 'v', label: '数值', placeholder: '数值', default: '0', sizeKey: 'subSize', colorKey: 'titleColor' },
      { key: 'd', label: '说明', placeholder: '说明', default: '-', multiline: true, sizeKey: 'dSize', colorKey: 'descColor' },
      { key: 'at', label: '出现时间(秒)', placeholder: '0', default: '0' },
    ], ['d', 'k', 'v']),
    mkNum(C_SIZE, '总标题字号', 56, 36, 120),
    mkColor('titleColor', '总标题颜色', '#FFFFFF'),
    mkNum(C_SUBSIZE, '数据行字号', 56, 30, 90),
    mkColor(C_ACCENT, '标签颜色', '#4CC9F0'),
    mkColor('descColor', '说明颜色', '#E6E6E6'),
    mkNum('dSize', '说明字号', 27, 16, 48),
  mkNum('posX', '左位置X', 130, 0, 1920, 1, 'px'),
    mkNum('posY', '顶部位置Y', 220, 0, 1080, 1, 'px'),
    mkNum('scale', '整体缩放', 100, 20, 200, 1, '%'),
  ],
  // ================= 第四大类 流程轨道 =================
  't4-01': [
    mkText('titleText', '主标题文案', '四步闭环运行流程', 'titleSize', 'titleColor'),
    mkList('steps', '流程步骤', JSON.stringify([
      { n: '01', t: '数据采集', d: '全域信息抓取收录' },
      { n: '02', t: '数据清洗', d: '无效信息过滤剔除' },
      { n: '03', t: '运算分析', d: '智能算法解析处理' },
      { n: '04', t: '结果输出', d: '精准结果落地反馈' },
    ]), [
      { key: 'n', label: '编号', placeholder: '编号', default: '01', sizeKey: 'numSize', colorKey: 'accentColor', note: '连接线/亮点颜色跟随此文本' },
      { key: 't', label: '步骤标题', placeholder: '步骤标题', default: '步骤', sizeKey: 'subSize', colorKey: 'titleColor' },
      { key: 'd', label: '步骤正文', placeholder: '步骤正文', default: '-', multiline: true, sizeKey: 'descSize', colorKey: 'dColor' },
    ]),
    mkNum(C_SIZE, '主标题字号', 56, 36, 120),
    mkColor('titleColor', '标题颜色', '#FFFFFF'),
    mkNum(C_SUBSIZE, '步骤标题字号', 34, 22, 60),
    mkColor(C_ACCENT, '序号/连接线颜色', '#4CC9F0'),
    mkNum('descSize', '正文字号', 19, 16, 56),
    mkColor('dColor', '正文颜色', '#E6E6E6'),
    mkNum('numSize', '编号字号', 30, 18, 60),
  mkNum('posX', '左位置X', 130, 0, 1920, 1, 'px'),
    mkNum('posY', '顶部位置Y', 240, 0, 1080, 1, 'px'),
    mkNum('scale', '整体缩放', 100, 20, 200, 1, '%'),
  ],
  't4-02': [
    mkText('titleText', '顶部标题', 'IDEA TO REAL APPLICATION', 'titleSize', 'titleColor'),
    mkList('nodes', '阶段节点', JSON.stringify([
      { cn: '学习研究', en: 'IDEA', color: '#36d8f0' },
      { cn: '个人创作', en: 'PROTOTYPE', color: '#36d8f0' },
      { cn: '产品开发', en: 'PRODUCT', color: '#42d2b8' },
      { cn: '商业应用', en: 'BUSINESS', color: '#f8b04e' },
    ]), [
      { key: 'cn', label: '中文标签', placeholder: '阶段', default: '阶段', sizeKey: 'cnSize', colorKey: 'cnColor' },
      { key: 'en', label: '英文标签', placeholder: 'STAGE', default: 'STAGE', sizeKey: 'enSize', colorKey: 'enColor' },
      { key: 'color', label: '节点颜色', placeholder: '#36d8f0', default: '#36d8f0', kind: 'color' },
    ], ['cn', 'en']),
    mkNum('titleSize', '标题字号', 38, 20, 80),
    mkColor('titleColor', '标题颜色', '#b4c8e0'),
    mkColor('frameColor', '外框颜色', '#406085'),
    mkColor('lineC1', '主线色1', '#36d8f0'),
    mkColor('lineC2', '主线色2', '#42d2b8'),
    mkColor('lineC3', '主线色3', '#f8b04e'),
    mkColor('ringColor', '外环深色', '#102035'),
    mkNum('ringR', '外环半径', 42, 24, 64),
    mkNum('cnSize', '中文标签字号', 52, 24, 80),
    mkColor('cnColor', '中文标签颜色', '#FFFFFF'),
    mkNum('enSize', '英文标签字号', 30, 16, 60),
    mkColor('enColor', '英文标签颜色', '#94acc8'),
    mkNum('scale', '整体缩放', 35, 20, 70, 1, '%'),
  mkNum('posX', '左位置X', 70, 0, 1920, 1, 'px'),
    mkNum('posY', '顶部位置Y', 320, 0, 1080, 1, 'px'),
  ],
  // ================= 第五大类 列表 =================
  't5-01': [
    mkText('titleText', '清单标题文案', '核心能力清单', 'titleSize', 'titleColor'),
    mkList('items', '数据条目', JSON.stringify([
      { t: '高速推理', d: '大模型本地高速推理，降低云端依赖' },
      { t: '低资源占用', d: '硬件开销可控，适配中端设备' },
      { t: '高扩展性', d: '插件化架构，支持自定义模块接入' },
    ]), [
      { key: 't', label: '条目标题', placeholder: '条目标题', default: '要点', sizeKey: 'subSize', colorKey: 'titleColor' },
      { key: 'd', label: '说明', placeholder: '说明', default: '-', multiline: true, sizeKey: 'descSize', colorKey: 'descColor' },
    ]),
    mkNum(C_SIZE, '清单标题字号', 54, 36, 120),
    mkColor(C_COLOR, '条目标题色', '#FFFFFF'),
    mkNum(C_SUBSIZE, '条目标题字号', 48, 26, 80),
    mkColor(C_ACCENT, '圆点颜色', '#4CC9F0'),
    mkNum('descSize', '说明字号', 34, 18, 60),
    mkColor('descColor', '说明颜色', '#E6E6E6'),
  mkNum('posX', '左位置X', 130, 0, 1920, 1, 'px'),
    mkNum('posY', '顶部位置Y', 220, 0, 1080, 1, 'px'),
    mkNum('scale', '整体缩放', 100, 20, 200, 1, '%'),
  ],
  't5-02': [
    mkText('titleText', '模块标题文案', '迭代任务状态', 'titleSize', 'tTitleColor'),
    mkList('items', '状态条目', JSON.stringify([
      { tag: 'DONE', t: '内核模块重构', d: '完成底层调度重写', color: '#06D6A0' },
      { tag: 'PROGRESS', t: '多模型调度', d: '兼容第三方模型接入', color: '#4CC9F0' },
      { tag: 'WARN', t: '内存回收', d: '极端场景存在泄漏风险', color: '#F72585' },
    ]), [
      { key: 'tag', label: '标签', placeholder: '标签', default: 'DONE', sizeKey: 'tagSize' },
      { key: 't', label: '条目标题', placeholder: '条目标题', default: '状态', sizeKey: 'subSize', colorKey: 'tColor' },
      { key: 'd', label: '说明', placeholder: '说明', default: '-', multiline: true, sizeKey: 'descSize', colorKey: 'descColor' },
      { key: 'color', label: '标签颜色', placeholder: '#4CC9F0', default: '#4CC9F0', kind: 'color' },
    ], ['d', 't', 'tag']),
    mkNum(C_SIZE, '模块标题字号', 54, 36, 120),
    mkColor('tTitleColor', '模块标题颜色', '#FFFFFF'),
    mkNum(C_SUBSIZE, '条目标题字号', 38, 22, 70),
    mkColor('tColor', '条目标题颜色', '#FFFFFF'),
    mkNum('tagSize', '标签字号', 26, 16, 48),
    mkNum('descSize', '说明字号', 30, 16, 48),
    mkColor('descColor', '说明颜色', '#E6E6E6'),
    mkColor('doneColor', '完成标签色', '#06D6A0'),
    mkColor('warnColor', '警告标签色', '#F72585'),
    mkColor(C_ACCENT, '进行中标签色', '#4CC9F0'),
  mkNum('posX', '左位置X', 130, 0, 1920, 1, 'px'),
    mkNum('posY', '顶部位置Y', 240, 0, 1080, 1, 'px'),
    mkNum('scale', '整体缩放', 100, 20, 200, 1, '%'),
  ],
  't5-03': [
    mkText('titleText', '章节标题文案', '系统优化三大方向', 'titleSize', 'titleColor'),
    mkList('items', '数据条目', JSON.stringify([
      { n: '01', t: '算力调度', d: '重新分配硬件资源，降低无效占用' },
      { n: '02', t: '缓存策略', d: '构建多级缓存，缩短数据读取耗时' },
      { n: '03', t: '链路裁剪', d: '剔除冗余逻辑，压缩整体执行链路' },
    ]), [
      { key: 'n', label: '序号', placeholder: '01', default: '01', sizeKey: 'numSize', colorKey: 'accentColor' },
      { key: 't', label: '条目标题', placeholder: '条目标题', default: '方向', sizeKey: 'subSize', colorKey: 'titleColor' },
      { key: 'd', label: '说明', placeholder: '说明', default: '-', multiline: true, sizeKey: 'descSize', colorKey: 'descColor' },
    ]),
    mkNum(C_SIZE, '章节标题字号', 56, 36, 120),
    mkColor(C_COLOR, '条目标题色', '#FFFFFF'),
    mkNum(C_SUBSIZE, '条目标题字号', 40, 24, 72),
    mkColor(C_ACCENT, '序号颜色', '#4CC9F0'),
    mkNum('numSize', '序号字号', 46, 24, 80),
    mkNum('descSize', '说明字号', 30, 16, 56),
    mkColor('descColor', '说明颜色', '#E6E6E6'),
  mkNum('posX', '左位置X', 130, 0, 1920, 1, 'px'),
    mkNum('posY', '顶部位置Y', 200, 0, 1080, 1, 'px'),
    mkNum('scale', '整体缩放', 100, 20, 200, 1, '%'),
  ],
  't5-04': [
    mkText('titleText', '模块标题文案', '版本基础信息', 'titleSize', 'titleColor'),
    mkList('items', '数据条目', JSON.stringify([
      { k: '版本号', v: 'V2.5.1' },
      { k: '发布时间', v: '2026-08' },
      { k: '目标平台', v: 'Windows / MacOS' },
      { k: '内核', v: 'Hyper-engine-v4' },
    ]), [
      { key: 'k', label: 'Key', placeholder: 'Key', default: '字段', sizeKey: 'subSize', colorKey: 'accentColor' },
      { key: 'v', label: 'Value', placeholder: 'Value', default: '-', multiline: true, sizeKey: 'subSize', colorKey: 'subColor' },
    ]),
    mkNum(C_SIZE, '模块标题字号', 54, 36, 120),
    mkColor('titleColor', '模块标题颜色', '#FFFFFF'),
    mkNum(C_SUBSIZE, '字段字号', 44, 24, 80),
    mkColor(C_ACCENT, 'Key颜色', '#4CC9F0'),
    mkColor(C_SUBCOLOR, 'Value颜色', '#E6E6E6'),
  mkNum('posX', '左位置X', 130, 0, 1920, 1, 'px'),
    mkNum('posY', '顶部位置Y', 240, 0, 1080, 1, 'px'),
    mkNum('scale', '整体缩放', 100, 20, 200, 1, '%'),
  ],
  't5-05': [
    mkList('cards', '标签卡片', JSON.stringify([
      { small: '工作强度', main: '持续上升', color: '#ffaa44' },
      { small: '人员经验', main: '存在差异', color: '#f24e78' },
      { small: '现场环境', main: '复杂多变', color: '#22ccf2' },
    ]), [
      { key: 'small', label: '小标题', placeholder: '小标题', default: '小标题', sizeKey: 'smallSize', colorKey: 'smallColor' },
      { key: 'main', label: '大标题', placeholder: '大标题', default: '大标题', sizeKey: 'mainSize', colorKey: 'mainColor' },
      { key: 'color', label: '竖条颜色', placeholder: '#ffaa44', default: '#ffaa44', kind: 'color' },
    ], ['main', 'small']),
    mkNum('smallSize', '小标题字号', 44, 20, 80),
    mkColor('smallColor', '小标题颜色', '#b8d0e8'),
    mkNum('mainSize', '大标题字号', 72, 32, 140),
    mkColor('mainColor', '大标题颜色', '#FFFFFF'),
    mkColor('cardBg', '卡片底色', 'rgba(12,26,44,0.72)'),
    mkNum('cardW', '卡片宽度', 780, 300, 1400),
    mkNum('gap', '卡片间距', 44, 12, 160),
    mkNum('scale', '整体缩放', 67, 20, 150, 1, '%'),
  mkNum('posX', '左位置X', 60, 0, 1920, 1, 'px'),
    mkNum('posY', '顶部位置Y', 80, 0, 1080, 1, 'px'),
  ],
  't5-06': [
    mkText('titleText', '总标题文案', '组件问题排查清单', 'titleSize', 'titleColor'),
    mkList('items', '信息条目', JSON.stringify([
      { label: '01 / 时间问题', title: '标题出场过早/动效拥挤', color: '#4CC9F0' },
      { label: '02 / 位置问题', title: '数字遮挡人物/框体偏大', color: '#FF5580' },
      { label: '03 / 交互问题', title: '按钮反馈缺失/手势不响应', color: '#FF5580' },
    ]), [
      { key: 'label', label: '红色标签', placeholder: '01 / 标签', default: '01 / 标签', sizeKey: 'labelSize', colorKey: 'labelColor' },
      { key: 'title', label: '条目标题', placeholder: '条目标题', default: '条目标题', sizeKey: 'itemSize', colorKey: 'itemColor' },
      { key: 'color', label: '标签/横线颜色', placeholder: '#FF5580', default: '#FF5580', kind: 'color' },
    ], ['label', 'title']),
    mkNum('titleSize', '总标题字号', 93, 40, 130),
    mkColor('titleColor', '总标题颜色', '#FFFFFF'),
    mkNum('labelSize', '标签字号', 24, 16, 60),
    mkColor('labelColor', '标签颜色', '#FF5580'),
    mkNum('itemSize', '条目标题字号', 30, 18, 66),
    mkColor('itemColor', '条目标题颜色', '#FFFFFF'),
    mkNum('lineW', '横线长度', 336, 160, 800),
    mkNum('lineH', '横线粗细', 3, 2, 18),
    mkColor('lineColor2', '横线渐变终点色', 'rgba(178,136,255,0.3)'),
    mkNum('colW', '每列宽', 381, 220, 900),
    mkNum('labelGap', '标签与标题间距', 26, 8, 60),
    mkNum('lineGap', '标题与横线间距', 22, 8, 60),
    mkNum('itemGap', '条目水平间距', 40, 20, 200),
    mkNum('scale', '整体缩放', 60, 30, 100, 1, '%'),
  mkNum('posX', '左位置X', 130, 0, 1920, 1, 'px'),
    mkNum('posY', '顶部位置Y', 200, 0, 1080, 1, 'px'),
  ],
  // ================= 第六大类 时间线流向 =================
  't6-01': [
    mkText('titleText', '时间线标题文案', '产品演进时间线', 'titleSize', 'titleColor'),
    mkColor(C_ACCENT, '轨道/节点色', '#4CC9F0'),
    mkList('nodes', '时间轴事件', JSON.stringify([
      { time: '2025-03', t: 'V1.0正式发布', d: '基础推理能力落地' },
      { time: '2025-11', t: 'V2.0大版本更新', d: '新增多任务调度模块' },
      { time: '2026-08', t: 'V2.5重大升级', d: '重构底层内核架构' },
    ]), [
      { key: 'time', label: '时间', placeholder: '2025-03', default: '2025-03', sizeKey: 'timeSize', colorKey: 'timeColor' },
      { key: 't', label: '事件标题', placeholder: '事件标题', default: '事件', sizeKey: 'subSize', colorKey: 'nodeColor' },
      { key: 'd', label: '说明', placeholder: '说明', default: '-', multiline: true, sizeKey: 'descSize', colorKey: 'descColor' },
    ]),
    mkNum(C_SIZE, '时间线标题字号', 54, 36, 120),
    mkColor('titleColor', '时间线标题颜色', '#FFFFFF'),
    mkNum(C_SUBSIZE, '节点标题字号', 40, 24, 72),
    mkColor('nodeColor', '节点标题颜色', '#FFFFFF'),
    mkNum('timeSize', '时间标签字号', 34, 18, 60),
    mkColor('timeColor', '时间标签颜色', '#4CC9F0'),
    mkNum('descSize', '说明字号', 36, 20, 56),
    mkColor('descColor', '说明颜色', '#E6E6E6'),
  mkNum('posX', '左位置X', 130, 0, 1920, 1, 'px'),
    mkNum('posY', '顶部位置Y', 200, 0, 1080, 1, 'px'),
    mkNum('scale', '整体缩放', 92, 20, 200, 1, '%'),
  ],
  't6-02': [
    mkText('titleText', '模块标题文案', '数据流转链路', 'titleSize', 'titleColor'),
    mkColor(C_ACCENT, '箭头颜色', '#4CC9F0'),
    mkList('nodes', '节点数组', JSON.stringify([
      { t: '输入', d: '原始数据接入' },
      { t: '处理', d: '算法运算解析' },
      { t: '输出', d: '结果对外返回' },
    ]), [
      { key: 't', label: '节点标题', placeholder: '节点标题', default: '节点', sizeKey: 'subSize', colorKey: 'nodeColor' },
      { key: 'd', label: '节点说明', placeholder: '说明', default: '-', multiline: true, sizeKey: 'descSize', colorKey: 'descColor' },
    ]),
    mkNum(C_SIZE, '模块标题字号', 54, 36, 120),
    mkColor('titleColor', '模块标题颜色', '#FFFFFF'),
    mkNum(C_SUBSIZE, '节点标题字号', 42, 24, 72),
    mkColor('nodeColor', '节点标题颜色', '#FFFFFF'),
    mkNum('descSize', '节点说明字号', 30, 18, 56),
    mkColor('descColor', '节点说明颜色', '#E6E6E6'),
  mkNum('posX', '左位置X', 130, 0, 1920, 1, 'px'),
    mkNum('posY', '顶部位置Y', 260, 0, 1080, 1, 'px'),
    mkNum('scale', '整体缩放', 100, 20, 200, 1, '%'),
  ],
  't6-03': [
    mkText('titleText', '进度标题文案', '项目整体完成度', 'titleSize', 'titleColor'),
    mkText('descText', '进度说明文案', '整体开发任务进度', 'descSize', 'descColor'),
    mkColor(C_LINE, '填充条颜色', '#4CC9F0'),
    mkNum(C_SIZE, '进度标题字号', 54, 36, 120),
    mkColor('titleColor', '进度标题颜色', '#FFFFFF'),
    mkNum(C_SUBSIZE, '数值字号', 48, 26, 80),
    mkColor(C_COLOR, '数值颜色', '#FFFFFF'),
    mkNum('descSize', '说明字号', 34, 20, 60),
    mkColor('descColor', '说明颜色', '#E6E6E6'),
  mkNum('posX', '左位置X', 130, 0, 1920, 1, 'px'),
    mkNum('posY', '顶部位置Y', 300, 0, 1080, 1, 'px'),
    mkNum('scale', '整体缩放', 100, 20, 200, 1, '%'),
  ],
  't6-04': [
    mkText('titleText', '主标题文案', '分支调度逻辑', 'titleSize', 'titleColor'),
    mkText('inText', '输入节点文案', '输入任务', 'inSize', 'inColor'),
    mkText('aText', '左分支文案', '高速路径', 'subSize', 'branchA', '分支线段颜色跟随此文本'),
    mkText('bText', '右分支文案', '深度路径', 'subSize', 'branchB', '分支线段颜色跟随此文本'),
    mkNum(C_SIZE, '主标题字号', 54, 36, 120),
    mkColor('titleColor', '主标题颜色', '#FFFFFF'),
    mkColor('branchA', '左分支颜色', '#4CC9F0'),
    mkColor('branchB', '右分支颜色', '#F72585'),
    mkNum(C_SUBSIZE, '节点标题字号', 42, 24, 72),
    mkNum('inSize', '输入节点字号', 44, 24, 80),
    mkColor('inColor', '输入节点颜色', '#FFFFFF'),
  mkNum('posX', '左位置X', 392, 0, 1920, 1, 'px'),
    mkNum('posY', '顶部位置Y', 230, 0, 1080, 1, 'px'),
    mkNum('scale', '整体缩放', 80, 20, 200, 1, '%'),
  ],
  't6-05': [
    mkText('stepText', 'STEP标签文案', 'STEP 02', 'stepSize', 'accentColor'),
    mkText('sloganText', '副标题文案', '做完一步 · 都会跟你对齐', 'sloganSize', 'sloganColor'),
    mkColor(C_ACCENT, '主题色(线/圆/STEP)', '#8B7CF0'),
    mkList('nodes', '步骤节点', JSON.stringify([
      { num: '01', t: '跟你对齐几个关键点', en: 'SYNC' },
      { num: '02', t: '这一步在做什么', en: 'WHAT NOW' },
      { num: '03', t: '推进到哪了', en: 'HOW FAR' },
      { num: '04', t: '想加想改随时改', en: 'TWEAK' },
    ]), [
      { key: 'num', label: '序号', placeholder: '01', default: '01', sizeKey: 'numSize', colorKey: 'numColor' },
      { key: 't', label: '标题', placeholder: '标题', default: '标题', sizeKey: 'subSize', colorKey: 'nodeColor' },
      { key: 'en', label: '英文说明', placeholder: 'SYNC', default: 'SYNC', sizeKey: 'enSize', colorKey: 'enColor' },
    ]),
    mkNum('stepSize', 'STEP字号', 48, 24, 80),
    mkNum('sloganSize', '副标题字号', 26, 16, 60),
    mkColor('sloganColor', '副标题颜色', '#9999AA'),
    mkNum('numSize', '序号字号', 32, 16, 64),
    mkColor('numColor', '序号颜色', '#FFFFFF'),
    mkNum(C_SUBSIZE, '节点标题字号', 46, 24, 72),
    mkColor('nodeColor', '节点标题颜色', '#FFFFFF'),
    mkNum('enSize', '英文说明字号', 24, 14, 56),
    mkColor('enColor', '英文说明颜色', '#9999AA'),
  mkNum('posX', '左位置X', 128, 0, 1920, 1, 'px'),
    mkNum('posY', '顶部位置Y', 40, 0, 1080, 1, 'px'),
    mkNum('scale', '整体缩放', 100, 20, 200, 1, '%'),
  ],
  't6-06': [
    mkText('titleText', '主标题文案', 'AI 迭代调试 · 循环推进', 'titleSize', 'titleColor'),
    mkList('steps', '步骤列表', JSON.stringify([
      { num: '01', t: '描述问题' },
      { num: '02', t: 'AI 改代码' },
      { num: '03', t: '重新渲染' },
      { num: '04', t: '打开看结果' },
    ]), [
      { key: 'num', label: '序号', placeholder: '01', default: '01', sizeKey: 'stepNumSize', colorKey: 'stepNumColor' },
      { key: 't', label: '步骤文字', placeholder: '步骤', default: '步骤', sizeKey: 'stepLabelSize', colorKey: 'stepLabelColor' },
    ]),
    mkText('footerText', '底部备注文案', '位置或时间还差一点，就重新循环', 'footerSize', 'footerColor'),
    mkNum('titleSize', '主标题字号', 64, 40, 120),
    mkColor('titleColor', '主标题颜色', '#FFFFFF'),
    mkNum('stepNumSize', '序号字号', 26, 24, 80),
    mkColor('stepNumColor', '序号颜色', '#9388FF'),
    mkNum('stepLabelSize', '步骤字号', 30, 28, 100),
    mkColor('stepLabelColor', '步骤文字颜色', '#FFFFFF'),
    mkNum('stepGap', '步骤间距', 12, 8, 160),
    mkNum('arrowSize', '箭头字号', 26, 24, 80),
    mkColor('arrowColor', '箭头颜色', '#B8AAFF'),
    mkNum('footerSize', '底部备注字号', 30, 20, 60),
    mkColor('footerColor', '底部备注颜色', '#B0B8E0'),
  mkNum('posX', '左位置X', 0, 0, 1920, 1, 'px'),
    mkNum('posY', '顶部位置Y', 0, 0, 1080, 1, 'px'),
    mkNum('scale', '整体缩放', 100, 20, 200, 1, '%'),
  ],
  // ================= 第七大类 迷你图表 =================
  't7-01': [
    mkText('titleText', '图表标题文案', '各版本推理速度对比', 'titleSize', 'titleColor'),
    mkList('items', '数据条目', JSON.stringify([
      { cat: 'V1.0', val: '28' },
      { cat: 'V2.0', val: '47' },
      { cat: 'V2.4', val: '66' },
      { cat: 'V2.5', val: '92', hl: '1' },
    ]), [
      { key: 'cat', label: '类目', placeholder: 'V1.0', default: 'V1.0', sizeKey: 'catSize', colorKey: 'catColor' },
      { key: 'val', label: '数值', placeholder: '50', default: '50', sizeKey: 'subSize', colorKey: 'valColor' },
      { key: 'hl', label: '高亮(填1)', placeholder: '0', default: '0' },
    ], ['cat', 'val']),
    mkNum(C_SIZE, '图表标题字号', 54, 36, 120),
    mkColor('titleColor', '图表标题颜色', '#FFFFFF'),
    mkColor('barA', '柱体颜色', '#4CC9F0'),
    mkColor('barB', '高亮柱颜色', '#F72585'),
    mkNum(C_SUBSIZE, '柱顶数值字号', 36, 20, 60),
    mkColor('valColor', '柱顶数值颜色', '#FFFFFF'),
    mkNum('catSize', '类目字号', 32, 18, 56),
    mkColor('catColor', '类目颜色', '#E6E6E6'),
  mkNum('posX', '左位置X', 130, 0, 1920, 1, 'px'),
    mkNum('posY', '顶部位置Y', 220, 0, 1080, 1, 'px'),
    mkNum('scale', '整体缩放', 100, 20, 200, 1, '%'),
  ],
  't7-02': [
    mkText('titleText', '图表标题文案', '资源占用对比', 'titleSize', 'titleColor'),
    mkColor(C_LINE, '填充条颜色', '#4CC9F0'),
    mkList('nodes', '类目数据', JSON.stringify([
      { cat: 'CPU占用', val: '62' },
      { cat: '内存占用', val: '48' },
      { cat: 'GPU占用', val: '76' },
    ]), [
      { key: 'cat', label: '类目名称', placeholder: 'CPU占用', default: '类目', sizeKey: 'catSize', colorKey: 'catColor' },
      { key: 'val', label: '数值(%)', placeholder: '60', default: '50', sizeKey: 'valSize', colorKey: 'valColor' },
    ]),
    mkNum(C_SIZE, '图表标题字号', 54, 36, 120),
    mkColor('titleColor', '图表标题颜色', '#FFFFFF'),
    mkNum('catSize', '类目字号', 42, 24, 72),
    mkColor('catColor', '类目颜色', '#FFFFFF'),
    mkNum('valSize', '数值字号', 38, 20, 64),
    mkColor('valColor', '数值颜色', '#FFFFFF'),
  mkNum('posX', '左位置X', 130, 0, 1920, 1, 'px'),
    mkNum('posY', '顶部位置Y', 240, 0, 1080, 1, 'px'),
    mkNum('scale', '整体缩放', 100, 20, 200, 1, '%'),
  ],
  't7-03': [
    mkText('titleText', '图表标题文案', '算力资源分配', 'titleSize', 'titleColor'),
    mkText('centerText', '中心标注文案', '总计', 'centerSize', 'centerColor'),
    mkList('segs', '数据条目', JSON.stringify([
      { name: '推理算力', pct: '60', color: '#4CC9F0' },
      { name: '缓存开销', pct: '25', color: '#06D6A0' },
      { name: '其他开销', pct: '15', color: '#F72585' },
    ]), [
      { key: 'name', label: '名称', placeholder: '推理算力', default: '名称', sizeKey: 'nameSize', colorKey: 'nameColor' },
      { key: 'pct', label: '占比(%)', placeholder: '60', default: '50', sizeKey: 'pctSize', colorKey: 'pctColor' },
      { key: 'color', label: '分区颜色', placeholder: '#4CC9F0', default: '#4CC9F0', kind: 'color' },
    ], ['name', 'pct']),
    mkNum(C_SIZE, '图表标题字号', 54, 36, 120),
    mkColor('titleColor', '图表标题颜色', '#FFFFFF'),
    mkNum('centerSize', '中心标注字号', 32, 18, 60),
    mkColor('centerColor', '中心标注颜色', '#E6E6E6'),
    mkNum('centerNumSize', '中心数值字号', 54, 24, 90),
    mkNum('nameSize', '名称字号', 34, 18, 60),
    mkColor('nameColor', '名称颜色', '#E6E6E6'),
    mkNum('pctSize', '占比字号', 34, 18, 60),
    mkColor('pctColor', '占比颜色', '#FFFFFF'),
  mkNum('posX', '左位置X', 130, 0, 1920, 1, 'px'),
    mkNum('posY', '顶部位置Y', 200, 0, 1080, 1, 'px'),
    mkNum('scale', '整体缩放', 100, 20, 200, 1, '%'),
  ],
  't7-04': [
    mkText('titleText', '图表标题文案', '吞吐量随负载变化', 'titleSize', 'titleColor'),
    mkList('lines', '折线数据', JSON.stringify([
      { name: 'A模型', color: '#4CC9F0', data: '12,27,44,61,78,92' },
      { name: 'B模型', color: '#F72585', data: '18,33,51,66,82,95' },
    ]), [
      { key: 'name', label: '图例文案', placeholder: 'A模型', default: 'A模型', sizeKey: 'legendSize', colorKey: 'legendColor' },
      { key: 'color', label: '线条颜色', placeholder: '#4CC9F0', default: '#4CC9F0', kind: 'color' },
      { key: 'data', label: '数据数组(逗号分隔)', placeholder: '12,27,44,61,78,92', default: '12,27,44,61,78,92', multiline: true },
    ], ['data', 'name']),
    mkText('xlText', '横轴标签(逗号分隔)', '20%,40%,60%,80%,100%,120%', 'subSize', 'xLabelColor'),
    mkColor('xLabelColor', '横轴文字颜色', '#E6E6E6'),
    mkNum(C_SIZE, '图表标题字号', 54, 36, 120),
    mkColor('titleColor', '图表标题颜色', '#FFFFFF'),
    mkNum(C_SUBSIZE, 'X标签字号', 30, 18, 52),
    mkNum('legendSize', '图例字号', 30, 18, 52),
    mkColor('legendColor', '图例颜色', '#FFFFFF'),
  mkNum('posX', '左位置X', 130, 0, 1920, 1, 'px'),
    mkNum('posY', '顶部位置Y', 260, 0, 1080, 1, 'px'),
    mkNum('scale', '整体缩放', 100, 20, 200, 1, '%'),
  ],
  't7-05': [
    mkText('titleText', '组标题文案', '核心指标快照', 'titleSize', 'titleColor'),
    mkList('cards', '指标条目', JSON.stringify([
      { name: '平均延迟', val: '24ms', delta: '↓18%', dir: 'down' },
      { name: '成功率', val: '97.2%', delta: '↑2.1%', dir: 'up' },
    ]), [
      { key: 'name', label: '指标名称', placeholder: '平均延迟', default: '指标', sizeKey: 'nameSize', colorKey: 'nameColor' },
      { key: 'val', label: '指标数值', placeholder: '24ms', default: '0', sizeKey: 'valSize', colorKey: 'valColor' },
      { key: 'delta', label: '变化标签', placeholder: '↓18%', default: '↑0%', sizeKey: 'deltaSize' },
      { key: 'dir', label: '方向(up/down)', placeholder: 'up', default: 'up' },
    ]),
    mkColor('upColor', '上升标签色', '#06D6A0'),
    mkColor('downColor', '下降标签色', '#F72585'),
    mkNum(C_SIZE, '组标题字号', 54, 36, 120),
    mkColor('titleColor', '组标题颜色', '#FFFFFF'),
    mkNum('nameSize', '指标名称字号', 36, 24, 64),
    mkColor('nameColor', '指标名称颜色', '#E6E6E6'),
    mkNum('valSize', '指标数值字号', 72, 40, 120),
    mkColor('valColor', '指标数值颜色', '#FFFFFF'),
    mkNum('deltaSize', '变化标签字号', 32, 20, 56),
  mkNum('posX', '左位置X', 130, 0, 1920, 1, 'px'),
    mkNum('posY', '顶部位置Y', 240, 0, 1080, 1, 'px'),
    mkNum('scale', '整体缩放', 100, 20, 200, 1, '%'),
  ],
  't7-06': [
    mkNum('percent', '占比百分比', 85, 0, 100, 1, '%'),
    mkText('labelText', '下方标签文案', '关键占比', 'labelSize', 'labelColor'),
    mkColor('trackColor', '底轨颜色', '#444852'),
    mkColor('arcColor', '进度弧颜色', '#2288dd'),
    mkNum('numSize', '大数字字号', 140, 40, 200),
    mkColor('numColor', '大数字颜色', '#e6e8ed'),
    mkNum('labelSize', '标签字号', 48, 20, 80),
    mkColor('labelColor', '标签颜色', '#b0b4bc'),
    mkColor('sliderFill', '滑块颜色', '#f0f2f6'),
    mkColor('glowColor', '光晕颜色', '#88ffbb'),
    mkNum('radius', '圆弧半径', 320, 120, 420),
    mkNum('strokeW', '弧线粗细', 36, 12, 64),
    mkNum('scale', '整体缩放', 40, 20, 70, 1, '%'),
  mkNum('posX', '左位置X', 60, 0, 1920, 1, 'px'),
    mkNum('posY', '顶部位置Y', 220, 0, 1080, 1, 'px'),
  ],
  // ================= S/特效 FX 系列（参照 example/FX-*） =================
  'fx-01': [
    mkColor('accent', '主色(高亮词/渐变线)', '#00A8FF'),
    mkText('enText', '英文标签', 'DOUBAO AUTO EDIT', 'enSize', 'enColor'),
    mkText('titleText', '标题文案(重点词用{{}}括起)', '{{自动}}剪辑', 'titleSize', 'titleColor', '渐变线颜色跟随此文本重点词', 'accent'),
    mkNum('enSize', '英文标签字号', 30, 16, 60),
    mkColor('enColor', '英文标签颜色', '#00A8FF'),
    mkNum('titleSize', '主标题字号', 126, 40, 160),
    mkColor('titleColor', '主标题颜色', '#FFFFFF'),
  mkNum('posX', '左位置X', 160, 0, 1920, 1, 'px'),
    mkNum('posY', '顶部位置Y', 250, 0, 1080, 1, 'px'),
    mkNum('scale', '整体缩放', 100, 20, 200, 1, '%'),
  ],
  'fx-02': [
    mkColor('accent', '主色(高亮词/渐变线)', '#2DD98A'),
    mkText('enText', '英文标签', 'OPEN SKILL RELEASE', 'enSize', 'enColor'),
    mkText('titleText', '标题文案(重点词用{{}}括起)', '现在{{公开}}', 'titleSize', 'titleColor', '渐变线颜色跟随此文本重点词', 'accent'),
    mkText('subText', '线下方小字', 'SKILL：现在公開', 'subSize', 'subColor'),
    mkNum('enSize', '英文标签字号', 30, 16, 60),
    mkColor('enColor', '英文标签颜色', '#2DD98A'),
    mkNum('titleSize', '主标题字号', 126, 40, 160),
    mkColor('titleColor', '主标题颜色', '#FFFFFF'),
    mkNum('subSize', '线下方小字字号', 22, 14, 48),
    mkColor('subColor', '线下方小字颜色', '#FFFFFF'),
  mkNum('posX', '左位置X', 160, 0, 1920, 1, 'px'),
    mkNum('posY', '顶部位置Y', 250, 0, 1080, 1, 'px'),
    mkNum('scale', '整体缩放', 100, 20, 200, 1, '%'),
  ],
  'fx-03': [
    mkColor('accent', '主色(警示条)', '#FF6B6B'),
    mkText('enText', '英文标签', 'NO MANUL EDITING', 'enSize', 'enColor'),
    mkText('cnText', '中文提示', '这条视频，没有经过人工剪辑', 'cnSize', 'cnColor'),
    mkNum('enSize', '英文标签字号', 26, 16, 60),
    mkColor('enColor', '英文标签颜色', '#FF6B6B'),
    mkNum('cnSize', '中文提示字号', 40, 20, 70),
    mkColor('cnColor', '中文提示颜色', '#FFFFFF'),
  mkNum('posX', '左位置X', 130, 0, 1920, 1, 'px'),
    mkNum('posY', '顶部位置Y', 260, 0, 1080, 1, 'px'),
    mkNum('scale', '整体缩放', 100, 20, 200, 1, '%'),
  ],
  'fx-04': [
    mkText('tagText', '顶部标签', '顶部标签放在这里', 'tagSize', 'tagColor'),
    mkText('titleText', '大标题文案', '大标题在此可编辑', 'titleSize', 'titleColor'),
    mkList('items', '指标条目', JSON.stringify([
      { name: '算力', val: '80', color: '#9357a0' },
      { name: '能效', val: '85', color: '#3f63ae' },
      { name: '精度', val: '90', color: '#f5d859' },
      { name: '速度', val: '75', color: '#8cc453' },
    ]), [
      { key: 'name', label: '指标名称', placeholder: '算力', default: '指标', sizeKey: 'nameSize' },
      { key: 'val', label: '指标数值', placeholder: '80', default: '80', sizeKey: 'pSize', colorKey: 'pColor' },
      { key: 'color', label: '指标颜色', placeholder: '#9357a0', default: '#9357a0', kind: 'color' },
    ], ['name', 'val']),
    mkNum('tagSize', '顶部标签字号', 24, 16, 48),
    mkColor('tagColor', '顶部标签颜色', '#d0df67'),
    mkColor('bgColor', '组件背景色', '#231815aa'),
    mkNum('titleSize', '大标题字号', 46, 24, 80),
    mkColor('titleColor', '大标题颜色', '#e9f4f1'),
    mkNum('nameSize', '指标名称字号', 24, 16, 48),
    mkNum('pSize', '指标数值字号', 30, 18, 64),
    mkColor('pColor', '指标数值颜色', '#e9f4f1'),
  mkNum('posX', '左位置X', 130, 0, 1920, 1, 'px'),
    mkNum('posY', '顶部位置Y', 240, 0, 1080, 1, 'px'),
    mkNum('scale', '整体缩放', 100, 20, 200, 1, '%'),
  ],
  'fx-05': [
    mkText('tagText', '胶囊标签文案', '标签标签', 'tagSize', 'themeColor'),
    mkText('title1', '标题第一行', '这是我的主标题', 'titleSize', 'titleColor'),
    mkText('title2', '标题第二行', '标题的第二行', 'titleSize', 'titleColor'),
    mkList('tags', '小标签数组', JSON.stringify([
      { t: '小标签一' },
      { t: '小标签二' },
      { t: '小标签三' },
    ]), [
      { key: 't', label: '小标签文字', placeholder: '小标签', default: '标签', sizeKey: 'gSize', colorKey: 'gColor' },
    ]),
    mkNum('tagSize', '胶囊标签字号', 24, 16, 48),
    mkColor('themeColor', '主题色(边框/横线/标签背景)', '#d0df67'),
    mkColor('bgColor', '组件背景色', '#00000099'),
    mkNum('titleSize', '标题字号', 52, 24, 90),
    mkColor('titleColor', '标题颜色', '#e9f4f1'),
    mkNum('gSize', '小标签字号', 20, 14, 44),
    mkColor('gColor', '小标签颜色', '#d0df67'),
  mkNum('posX', '左位置X', 160, 0, 1920, 1, 'px'),
    mkNum('posY', '顶部位置Y', 210, 0, 1080, 1, 'px'),
    mkNum('scale', '整体缩放', 100, 20, 200, 1, '%'),
  ],
  'fx-06': [
    mkText('tagText', '顶部标签', '顶部标签', 'tagSize', 'tagColor'),
    mkText('titleText', '大标题文案', '大标题在此可编辑', 'titleSize', 'titleColor'),
    mkList('steps', '步骤数组', JSON.stringify([
      { n: '01', t: '数据采集', d: '全域信息抓取收录' },
      { n: '02', t: '智能解析', d: '算法深度处理' },
      { n: '03', t: '结果输出', d: '结果实时反馈' },
    ]), [
      { key: 'n', label: '步骤序号', placeholder: '01', default: '01', sizeKey: 'nSize', colorKey: 'nColor' },
      { key: 't', label: '步骤标题', placeholder: '步骤', default: '步骤', sizeKey: 'tSize', colorKey: 'tColor' },
      { key: 'd', label: '步骤说明', placeholder: '说明', default: '-', sizeKey: 'dSize', colorKey: 'dColor' },
    ]),
    mkText('footText', '补充说明', '补充说明1234567890', 'footSize', 'footColor'),
    mkNum('tagSize', '顶部标签字号', 24, 16, 48),
    mkColor('tagColor', '顶部标签颜色', '#d0df67'),
    mkColor('themeColor', '主题色(边框/横线/卡片边框)', '#d0df67'),
    mkColor('bgColor', '组件背景色', '#231815aa'),
    mkNum('titleSize', '大标题字号', 44, 24, 80),
    mkColor('titleColor', '大标题颜色', '#e9f4f1'),
    mkNum('nSize', '行序号字号', 28, 16, 60),
    mkColor('nColor', '行序号颜色', '#d0df67'),
    mkNum('tSize', '行标题字号', 28, 16, 60),
    mkColor('tColor', '行标题颜色', '#e9f4f1'),
    mkNum('dSize', '行说明字号', 22, 14, 48),
    mkColor('dColor', '行说明颜色', '#e9f4f1'),
    mkNum('footSize', '补充说明字号', 20, 14, 44),
    mkColor('footColor', '补充说明颜色', '#e9f4f1'),
  mkNum('posX', '左位置X', 130, 0, 1920, 1, 'px'),
    mkNum('posY', '顶部位置Y', 240, 0, 1080, 1, 'px'),
    mkNum('scale', '整体缩放', 100, 20, 200, 1, '%'),
  ],
  'fx-07': [
    mkText('tagText', '顶部标签', '顶部标签', 'tagSize', 'tagColor'),
    mkText('titleText', '大标题文案', '大标题在此可编辑', 'titleSize', 'titleColor'),
    mkList('cards', '小卡片数组', JSON.stringify([
      { t: '小标题1', d: '小标题1说明放在这里' },
      { t: '小标题2', d: '小标题2说明放在这里' },
      { t: '小标题3', d: '小标题3说明放在这里' },
      { t: '小标题4', d: '小标题4说明放在这里' },
    ]), [
      { key: 't', label: '卡片标题', placeholder: '标题', default: '小标题', sizeKey: 'ctSize', colorKey: 'ctColor' },
      { key: 'd', label: '卡片说明', placeholder: '说明', default: '说明文字', multiline: true, sizeKey: 'cdSize', colorKey: 'cdColor' },
    ]),
    mkText('footText', '补充说明', '补充说明1234567890', 'footSize', 'footColor'),
    mkNum('tagSize', '顶部标签字号', 24, 16, 48),
    mkColor('tagColor', '顶部标签颜色', '#d0df67'),
    mkColor('themeColor', '主题色(边框/横线/卡片边框)', '#d0df67'),
    mkColor('bgColor', '组件背景色', '#231815aa'),
    mkNum('titleSize', '大标题字号', 44, 24, 80),
    mkColor('titleColor', '大标题颜色', '#e9f4f1'),
    mkNum('ctSize', '卡片标题字号', 26, 16, 56),
    mkColor('ctColor', '卡片标题颜色', '#e9f4f1'),
    mkNum('cdSize', '卡片说明字号', 20, 14, 44),
    mkColor('cdColor', '卡片说明颜色', '#e9f4f1'),
    mkNum('footSize', '补充说明字号', 20, 14, 44),
    mkColor('footColor', '补充说明颜色', '#e9f4f1'),
  mkNum('posX', '左位置X', 130, 0, 1920, 1, 'px'),
    mkNum('posY', '顶部位置Y', 240, 0, 1080, 1, 'px'),
    mkNum('scale', '整体缩放', 100, 20, 200, 1, '%'),
  ],
  'fx-08': [
    mkText('tagText', '顶部标签', '顶部标签', 'tagSize', 'tagColor'),
    mkText('titleText', '大标题文案', '大标题在此可编辑', 'titleSize', 'titleColor'),
    mkList('bars', '进度条目', JSON.stringify([
      { n: '小标题一', g: '80', color: '#9357a0' },
      { n: '小标题二', g: '50', color: '#3f63ae' },
      { n: '小标题三', g: '73', color: '#f5d859' },
      { n: '小标题四', g: '60', color: '#8cc453' },
    ]), [
      { key: 'n', label: '条目名称', placeholder: '小标题', default: '条目', sizeKey: 'nSize', colorKey: 'nColor' },
      { key: 'g', label: '进度值', placeholder: '80', default: '80', sizeKey: 'gSize' },
      { key: 'color', label: '条目颜色', placeholder: '#9357a0', default: '#9357a0', kind: 'color' },
    ], ['g', 'n']),
    mkNum('tagSize', '顶部标签字号', 24, 16, 48),
    mkColor('tagColor', '顶部标签颜色', '#d0df67'),
    mkColor('bgColor', '组件背景色', '#231815aa'),
    mkNum('titleSize', '大标题字号', 42, 24, 80),
    mkColor('titleColor', '大标题颜色', '#e9f4f1'),
    mkNum('nSize', '条目名称字号', 22, 14, 48),
    mkColor('nColor', '条目名称颜色', '#e9f4f1'),
    mkNum('gSize', '进度百分比字号', 22, 14, 48),
  mkNum('posX', '左位置X', 130, 0, 1920, 1, 'px'),
    mkNum('posY', '顶部位置Y', 240, 0, 1080, 1, 'px'),
    mkNum('scale', '整体缩放', 100, 20, 200, 1, '%'),
  ],
  'fx-09': [
    mkColor('bgColor', '组件背景色', '#000000'),
    mkText('tagText', '标签文案', 'LAST EPISODE', 'tagSize', 'tagColor'),
    mkText('subText', '副标题文案', '上条 · 全网观看', 'subSize', 'subColor'),
    mkText('plusText', '加号字符', '+', 'plusSize', 'plusColor'),
    mkText('sourceText', '来源文案', 'AI 视频动效编辑台 · 的分享', 'sourceSize', 'sourceColor'),
    mkText('numText', '主数字', '48837', 'numSize', 'numColor'),
    mkNum('numSize', '主数字字号', 110, 40, 180),
    mkColor('numColor', '主数字颜色', '#FFFFFF'),
    mkNum('tagSize', '标签字号', 28, 16, 60),
    mkColor('tagColor', '标签颜色', '#8B7FD4'),
    mkNum('subSize', '副标题字号', 22, 14, 48),
    mkColor('subColor', '副标题颜色', '#999999'),
    mkNum('plusSize', '加号字号', 46, 20, 90),
    mkColor('plusColor', '加号颜色', '#8B7FD4'),
    mkNum('sourceSize', '来源字号', 20, 14, 44),
    mkColor('sourceColor', '来源颜色', '#A0A0AA'),
  mkNum('posX', '左位置X', 130, 0, 1920, 1, 'px'),
    mkNum('posY', '顶部位置Y', 240, 0, 1080, 1, 'px'),
    mkNum('scale', '整体缩放', 100, 20, 200, 1, '%'),
  ],
};

/**
 * 已在属性面板调好的导出配置（motion-config-2026-08-30.json）。
 * 作为各组件默认值；只覆盖 CONFIGS 中存在的键，避免写入遗留字段。
 */
export const DEFAULTS: Record<string, ConfigState> = {
  'fx-01': {
    accent: '#00a8ff', enText: 'DOUBAO AUTO EDIT', titleText: '{{自动}}剪辑',
    enSize: 30, enColor: '#00a8ff', titleSize: 126, titleColor: '#FFFFFF',
  posX: 160,
    posY: 250,
    scale: 100,
  },
  'fx-02': {
    accent: '#2DD98A', enText: 'OPEN SKILL RELEASE', titleText: '现在{{公开}}',
    subText: 'SKILL：现在公開', enSize: 30, enColor: '#2DD98A', titleSize: 126,
    titleColor: '#FFFFFF', subSize: 22, subColor: '#FFFFFF',
  posX: 160,
    posY: 250,
    scale: 100,
  },
  'fx-03': {
    accent: '#FF6B6B', enText: 'NO MANUL EDITING', cnText: '这条视频，没有经过人工剪辑',
    enSize: 16, enColor: '#FF6B6B', cnSize: 36, cnColor: '#FFFFFF',
  posX: 130,
    posY: 260,
    scale: 100,
  },
  'fx-04': {
    tagText: '顶部标签放在这里', titleText: '大标题在此可编辑',
    items: JSON.stringify([
      { name: '算力', val: '80', color: '#9357a0' },
      { name: '能效', val: '85', color: '#3f63ae' },
      { name: '精度', val: '90', color: '#f5d859' },
      { name: '速度', val: '75', color: '#8cc453' },
    ]),
    tagSize: 24, tagColor: '#d0df67', bgColor: '#231815aa', titleSize: 46,
    titleColor: '#e9f4f1', nameSize: 19, pSize: 30, pColor: '#e9f4f1',
  posX: 130,
    posY: 240,
    scale: 100,
  },
  'fx-05': {
    tagText: '标签标签', title1: '这是我的主标题', title2: '标题的第二行',
    tags: JSON.stringify([{ t: '小标签一' }, { t: '小标签二' }, { t: '小标签三' }]),
    tagSize: 16, themeColor: '#d0df67', bgColor: 'rgba(12,14,11,0.6)', titleSize: 52,
    titleColor: 'rgba(255,255,255,0.96)', gSize: 16, gColor: '#d0df67',
  posX: 160,
    posY: 210,
    scale: 100,
  },
  'fx-06': {
    tagText: '顶部标签', titleText: '大标题在此可编辑',
    steps: JSON.stringify([
      { n: '01', t: '数据采集', d: '全域信息抓取收录' },
      { n: '02', t: '智能解析', d: '算法深度处理' },
      { n: '03', t: '结果输出', d: '结果实时反馈' },
    ]),
    footText: '补充说明1234567890', tagSize: 21, tagColor: '#d0df67',
    themeColor: '#d0df67', bgColor: 'rgba(12,14,11,0.6)', titleSize: 44, titleColor: '#e9f4f1',
    nSize: 16, nColor: '#d0df67', tSize: 25, tColor: '#e9f4f1',
    dSize: 17, dColor: '#e9f4f1', footSize: 20, footColor: '#e9f4f1',
  posX: 130,
    posY: 240,
    scale: 100,
  },
  'fx-07': {
    tagText: '顶部标签', titleText: '大标题在此可编辑',
    cards: JSON.stringify([
      { t: '小标题1', d: '小标题1说明放在这里' },
      { t: '小标题2', d: '小标题2说明放在这里' },
      { t: '小标题3', d: '小标题3说明放在这里' },
      { t: '小标题4', d: '小标题4说明放在这里' },
    ]),
    footText: '补充说明1234567890', tagSize: 21, tagColor: '#d0df67',
    themeColor: '#d0df67', bgColor: 'rgba(12,14,11,0.6)', titleSize: 44, titleColor: '#e9f4f1',
    ctSize: 24, ctColor: '#e9f4f1', cdSize: 20, cdColor: '#e9f4f1',
    footSize: 20, footColor: '#e9f4f1',
  posX: 130,
    posY: 240,
    scale: 100,
  },
  'fx-08': {
    tagText: '顶部标签', titleText: '大标题在此可编辑',
    bars: JSON.stringify([
      { n: '小标题一', g: '80', color: '#9357a0' },
      { n: '小标题二', g: '50', color: '#3f63ae' },
      { n: '小标题三', g: '73', color: '#f5d859' },
      { n: '小标题四', g: '60', color: '#8cc453' },
    ]),
    tagSize: 20, tagColor: '#d0df67', bgColor: 'rgba(12,14,11,0.6)', titleSize: 42,
    titleColor: '#e9f4f1', nSize: 22, nColor: '#e9f4f1', gSize: 22,
  posX: 130,
    posY: 240,
    scale: 100,
  },
  'fx-09': {
    bgColor: 'rgba(0,0,0,0.69)', tagText: 'LAST EPISODE', subText: '全网观看数',
    plusText: '+', sourceText: '2026年累计AI 视频的播放量', numText: '48837',
    numSize: 110, numColor: '#FFFFFF', tagSize: 21, tagColor: '#8B7FD4',
    subSize: 22, subColor: '#999999', plusSize: 46, plusColor: '#8B7FD4',
    sourceSize: 20, sourceColor: '#A0A0AA',
  posX: 130,
    posY: 240,
    scale: 100,
  },
  't1-01': {
    tagText: 'LOOP', enText: 'TECHNOLOGY ANALYSIS', titleText: 'AI智能算法迭代升级',
    subText: '基于深度学习的全新算力优化方案', titleSize: 61, titleColor: '#FFFFFF',
    subSize: 26, subColor: '#E6E6E6', accentColor: '#4CC9F0', tagSize: 20, enSize: 21,
  posX: 1220,
    posY: 160,
    scale: 100,
  },
  't1-02': {
    quoteText: '“技术迭代的核心，是效率与体验的双向突破”',
    noteText: '行业核心共识 · 2026技术发展准则', lineColor: '#4CC9F0',
    subSize: 46, titleColor: '#FFFFFF', titleSize: 25, noteColor: '#E6E6E6',
  posX: 140,
    posY: 220,
    scale: 100,
  },
  't1-03': {
    noteText: '核心技术亮点', titleText: '全域智能感知系统', subSize: 30,
    subColor: '#4CC9F0', titleSize: 58, titleColor: '#FFFFFF',
  posX: 130,
    posY: 180,
    scale: 100,
  },
  't1-04': {
    tagText: 'TECH PROGRESS', titleText: '算力效能全面升级',
    descText: '突破传统算力瓶颈，实现全域效率提升', subSize: 23, accentColor: '#4CC9F0',
    titleSize: 60, titleColor: '#FFFFFF', descSize: 25, descColor: 'rgba(255,255,255,0.36)',
  posX: 130,
    posY: 180,
    scale: 100,
  },
  't1-05': {
    titleText: '智能化场景落地应用', descText: '多场景适配 · 高兼容 · 低损耗运行机制',
    lineColor: '#4CC9F0', titleSize: 58, titleColor: '#FFFFFF', subSize: 26, descColor: '#E6E6E6',
  posX: 130,
    posY: 200,
    scale: 100,
  },
  't1-06': {
    enText: 'SUMMARY', titleText: '技术体系整体总结',
    descText: '完成全链路技术闭环，实现高效稳定运行', lineColor: '#4CC9F0',
    subSize: 20, accentColor: '#4CC9F0', titleSize: 59, titleColor: '#FFFFFF',
    descSize: 24, descColor: '#E6E6E6',
  posX: 130,
    posY: 200,
    scale: 100,
  },
  't1-07': {
    kickerText: 'DATA DRIVEN', topText: '数据驱动智能升级',
    descText: '以数据为核心，重构智能运行逻辑', titleSize: 56, titleColor: '#FFFFFF',
    kickerSize: 23, kickerColor: 'rgba(255,255,255,0.28)', descSize: 25,
    descColor: '#E6E6E6',
  posX: 130,
    posY: 200,
    scale: 100,
  },
  't1-08': {
    tagText: 'CORE LOGIC', titleText: '核心运行逻辑解析',
    bodyText: '依托自适应算法，系统可实时调整运行策略，规避无效算力消耗，实现高效运转。',
    hlColor: '#4CC9F0', subSize: 25, accentColor: '#C77DFF', titleSize: 60,
    titleColor: '#FFFFFF', bodySize: 27, bodyColor: '#E6E6E6',
  posX: 130,
    posY: 180,
    scale: 100,
  },
  't1-09': {
    bodyText: '全链路智能化改造，实现降本增效核心目标', noteText: '数据统计周期：2026全年',
    titleSize: 50, titleColor: '#FFFFFF', subSize: 32, accentColor: '#4CC9F0',
  posX: 130,
    posY: 300,
    scale: 100,
  },
  't2-01': {
    contentText: '核心技术突破，实现行业领先层级效能', borderStart: '#4CC9F0',
    borderEnd: '#C77DFF', titleSize: 52, titleColor: '#FFFFFF',
  posX: 130,
    posY: 240,
    scale: 100,
  },
  't2-02': {
    tagText: 'CORE ACHIEVEMENT', titleText: '核心技术成果落地', lineColor: '#4CC9F0',
    subSize: 25, accentColor: '#4CC9F0', titleSize: 52, titleColor: '#FFFFFF',
  posX: 130,
    posY: 220,
    scale: 100,
  },
  't2-03': {
    titleText: '核心优势亮点', descText: '低功耗、高效率、高兼容的一体化运行体系',
    accentColor: 'rgba(76,201,240,0.08)', titleSize: 54, titleColor: '#FFFFFF',
    subSize: 25, descColor: '#E6E6E6',
  posX: 130,
    posY: 240,
    scale: 100,
  },
  't3-01': {
    noteText: '整体运算效率', unitText: 'FPS', descText: '超高帧率稳定运行，无卡顿延迟',
    value: 120, titleSize: 200, titleColor: '#FFFFFF', unitSize: 80, accentColor: '#4CC9F0',
    subSize: 36, noteColor: '#E6E6E6', descSize: 38, descColor: '#E6E6E6',
  posX: 130,
    posY: 200,
    scale: 100,
  },
  't3-02': {
    tagText: '算力提升', unitText: '%', descText: '核心指标对比基准', value: 58,
    subSize: 48, accentColor: '#4CC9F0', titleSize: 180, titleColor: '#FFFFFF',
    unitSize: 64, descSize: 36, descColor: '#E6E6E6',
  posX: 130,
    posY: 240,
    scale: 70,
  },
  't3-03': {
    labelL: '优化前', labelR: '优化后', descL: '基础算力水准', descR: '全新算力水准',
    valueL: 45, valueR: 92, accentColor: '#4CC9F0', accent2: '#F72585', labelSize: 40,
    titleSize: 160, titleColor: '#FFFFFF', descSize: 38, descColor: '#E6E6E6',
  posX: 130,
    posY: 240,
    scale: 100,
  },
  't3-04': {
    titleText: '核心参数指标',
    rows: JSON.stringify([
      { k: '延迟', v: '8ms', d: '超低运行延迟', at: 0 },
      { k: '功耗', v: '12W', d: '低功耗运行', at: 0.5 },
      { k: '准确率', v: '99.6%', d: '超高识别精度', at: 1 },
      { k: '参数', v: '100', d: '做出解释', at: 1.5 },
    ]),
    titleSize: 56, titleColor: '#FFFFFF', subSize: 33, accentColor: '#4CC9F0',
    descColor: '#E6E6E6', dSize: 27,
  posX: 130,
    posY: 220,
    scale: 100,
  },
  't4-01': {
    titleText: '多步闭环运行流程',
    steps: JSON.stringify([
      { n: '01', t: '数据采集', d: '全域信息抓取收录' },
      { n: '02', t: '数据清洗', d: '无效信息过滤剔除' },
      { n: '03', t: '运算分析', d: '智能算法解析处理' },
      { n: '04', t: '结果输出', d: '精准结果落地反馈' },
    ]),
    titleSize: 56, titleColor: '#FFFFFF', subSize: 34, accentColor: '#4CC9F0',
    descSize: 19, dColor: '#E6E6E6', numSize: 30,
  posX: 130,
    posY: 240,
    scale: 100,
  },
  't4-02': {
    titleText: 'IDEA TO REAL APPLICATION',
    nodes: JSON.stringify([
      { cn: '学习研究', en: 'IDEA', color: '#36d8f0' },
      { cn: '个人创作', en: 'PROTOTYPE', color: '#36d8f0' },
      { cn: '产品开发', en: 'PRODUCT', color: '#42d2b8' },
      { cn: '商业应用', en: 'BUSINESS', color: '#f8b04e' },
    ]),
    titleSize: 38, titleColor: '#b4c8e0', frameColor: '#406085',
    lineC1: '#36d8f0', lineC2: '#42d2b8', lineC3: '#f8b04e',
    ringColor: '#102035', ringR: 42, cnSize: 52, cnColor: '#FFFFFF',
    enSize: 30, enColor: '#94acc8', scale: 35,
  posX: 70,
    posY: 320,
  },
  't5-01': {
    titleText: '核心能力清单',
    items: JSON.stringify([
      { t: '高速推理', d: '大模型本地高速推理，降低云端依赖' },
      { t: '低资源占用', d: '硬件开销可控，适配中端设备' },
      { t: '高扩展性', d: '插件化架构，支持自定义模块接入' },
    ]),
    titleSize: 54, titleColor: '#FFFFFF', subSize: 29, accentColor: '#4CC9F0',
    descSize: 22, descColor: '#E6E6E6',
  posX: 130,
    posY: 220,
    scale: 100,
  },
  't5-02': {
    titleText: '迭代任务状态',
    items: JSON.stringify([
      { tag: 'DONE', t: '内核模块重构', d: '完成底层调度重写', color: '#06D6A0' },
      { tag: 'PROGRESS', t: '多模型调度', d: '兼容第三方模型接入', color: '#4CC9F0' },
      { tag: 'WARN', t: '内存回收', d: '极端场景存在泄漏风险', color: '#F72585' },
    ]),
    titleSize: 54, tTitleColor: '#FFFFFF', subSize: 33, tColor: '#FFFFFF', tagSize: 17,
    descSize: 22, descColor: '#E6E6E6', doneColor: '#06D6A0', warnColor: '#F72585',
    accentColor: '#4CC9F0',
  posX: 130,
    posY: 240,
    scale: 100,
  },
  't5-03': {
    titleText: '系统优化三大方向',
    items: JSON.stringify([
      { n: '01', t: '算力调度', d: '重新分配硬件资源，降低无效占用' },
      { n: '02', t: '缓存策略', d: '构建多级缓存，缩短数据读取耗时' },
      { n: '03', t: '链路裁剪', d: '剔除冗余逻辑，压缩整体执行链路' },
    ]),
    titleSize: 56, titleColor: '#FFFFFF', subSize: 38, accentColor: '#4CC9F0',
    numSize: 28, descSize: 25, descColor: '#E6E6E6',
  posX: 130,
    posY: 200,
    scale: 100,
  },
  't5-04': {
    titleText: '版本基础信息',
    items: JSON.stringify([
      { k: '版本号', v: 'V2.5.1' },
      { k: '发布时间', v: '2026-08' },
      { k: '目标平台', v: 'Windows / MacOS' },
      { k: '内核', v: 'Hyper-engine-v4' },
    ]),
    titleSize: 54, titleColor: '#FFFFFF', subSize: 25, accentColor: '#4CC9F0', subColor: '#E6E6E6',
  posX: 130,
    posY: 240,
    scale: 100,
  },
  't5-05': {
    cards: JSON.stringify([
      { small: '工作强度', main: '持续上升', color: '#ffaa44' },
      { small: '人员经验', main: '存在差异', color: '#f24e78' },
      { small: '现场环境', main: '复杂多变', color: '#22ccf2' },
    ]),
    smallSize: 32, smallColor: '#b8d0e8', mainSize: 51, mainColor: '#FFFFFF',
    cardBg: 'rgba(12,26,44,0.72)', cardW: 728, gap: 44, scale: 67,
  posX: 60,
    posY: 80,
  },
  't5-06': {
    titleText: '组件问题排查清单',
    items: JSON.stringify([
      { label: '01 / 时间问题', title: '标题出场过早/动效拥挤', color: '#4CC9F0' },
      { label: '02 / 位置问题', title: '数字遮挡人物/框体偏大', color: '#FF5580' },
      { label: '03 / 交互问题', title: '按钮反馈缺失/手势不响应', color: '#FF5580' },
    ]),
    titleSize: 93, titleColor: '#FFFFFF',
    labelSize: 24, labelColor: '#FF5580',
    itemSize: 30, itemColor: '#FFFFFF',
    lineW: 336, lineH: 3, lineColor2: 'rgba(178,136,255,0.3)',
    colW: 381, labelGap: 26, lineGap: 22, itemGap: 40, scale: 60,
  posX: 130,
    posY: 200,
  },
  't6-01': {
    titleText: '产品演进时间线', accentColor: '#4CC9F0', titleSize: 54,
    titleColor: '#FFFFFF', subSize: 32, timeSize: 27, timeColor: '#4CC9F0',
    nodeColor: '#FFFFFF', descSize: 22, descColor: '#E6E6E6',
    nodes: JSON.stringify([
      { time: '2025-03', t: 'V1.0正式发布', d: '基础推理能力落地' },
      { time: '2025-11', t: 'V2.0大版本更新', d: '新增多任务调度模块' },
      { time: '2026-08', t: 'V2.5重大升级', d: '重构底层内核架构' },
    ]),
  posX: 130,
    posY: 200,
    scale: 100,
  },
  't6-02': {
    titleText: '数据流转链路', accentColor: '#4CC9F0', titleSize: 54,
    titleColor: '#FFFFFF', subSize: 30, nodeColor: '#FFFFFF', descSize: 20, descColor: '#E6E6E6',
    nodes: JSON.stringify([
      { t: '输入', d: '原始数据接入' },
      { t: '处理', d: '算法运算解析' },
      { t: '输出', d: '结果对外返回' },
      { t: '打印', d: '数据打印输出' },
    ]),
  posX: 130,
    posY: 260,
    scale: 100,
  },
  't6-03': {
    titleText: '项目整体完成度', descText: '整体开发任务进度', lineColor: '#4CC9F0',
    titleSize: 54, titleColor: '#FFFFFF', subSize: 40, descSize: 25, descColor: '#E6E6E6',
  posX: 130,
    posY: 300,
    scale: 100,
  },
  't6-04': {
    titleText: '分支调度逻辑', inText: '输入任务', aText: '高速路径', bText: '深度路径',
    titleSize: 54, titleColor: '#FFFFFF', branchA: '#4CC9F0', branchB: '#F72585',
    subSize: 24, inSize: 24, inColor: '#FFFFFF',
  posX: 392,
    posY: 230,
    scale: 80,
  },
  't6-05': {
    stepText: 'STEP 02', sloganText: '做完一步 · 都会跟你对齐',
    accentColor: '#8B7CF0', stepSize: 48, sloganSize: 26, sloganColor: '#9999AA',
    numSize: 20, numColor: '#FFFFFF', subSize: 29, nodeColor: '#FFFFFF',
    enSize: 21, enColor: '#9999AA',
    nodes: JSON.stringify([
      { num: '01', t: '跟你对齐几个关键点', en: 'SYNC' },
      { num: '02', t: '这一步在做什么', en: 'WHAT NOW' },
      { num: '03', t: '推进到哪了', en: 'HOW FAR' },
      { num: '04', t: '想加想改随时改', en: 'TWEAK' },
    ]),
  posX: 260,
    posY: 40,
    scale: 100,
  },
  't6-06': {
    titleText: 'AI 迭代调试 · 循环推进', titleSize: 64, titleColor: '#FFFFFF',
    stepNumSize: 26, stepNumColor: '#9388FF', stepLabelSize: 30, stepLabelColor: '#FFFFFF',
    stepGap: 12, arrowSize: 26, arrowColor: '#B8AAFF',
    footerText: '位置或时间还差一点，就重新循环', footerSize: 30, footerColor: '#B0B8E0',
    steps: JSON.stringify([
      { num: '01', t: '描述问题' },
      { num: '02', t: 'AI 改代码' },
      { num: '03', t: '重新渲染' },
      { num: '04', t: '打开看结果' },
    ]),
  posX: 0,
    posY: 0,
    scale: 100,
  },
  't7-01': {
    titleText: '各版本推理速度对比',
    items: JSON.stringify([
      { cat: 'V1.0', val: '28', hl: '0' },
      { cat: 'V2.0', val: '47' },
      { cat: 'V2.4', val: '66' },
      { cat: 'V2.5', val: '92', hl: '1' },
    ]),
    titleSize: 54, titleColor: '#FFFFFF', barA: '#4CC9F0', barB: '#F72585',
    subSize: 25, valColor: '#FFFFFF', catSize: 25, catColor: '#E6E6E6',
  posX: 130,
    posY: 220,
    scale: 100,
  },
  't7-02': {
    titleText: '资源占用对比', lineColor: '#4CC9F0', titleSize: 54,
    titleColor: '#FFFFFF', catSize: 30, catColor: '#FFFFFF', valSize: 30, valColor: '#FFFFFF',
    nodes: JSON.stringify([
      { cat: 'CPU占用', val: '62' },
      { cat: '内存占用', val: '48' },
      { cat: 'GPU占用', val: '76' },
    ]),
  posX: 130,
    posY: 240,
    scale: 100,
  },
  't7-03': {
    titleText: '算力资源分配', centerText: '总计', titleSize: 54, titleColor: '#FFFFFF',
    centerSize: 27, centerColor: '#E6E6E6', centerNumSize: 38, nameSize: 26, nameColor: '#E6E6E6',
    pctSize: 26, pctColor: '#FFFFFF',
    segs: JSON.stringify([
      { name: '推理算力', pct: '60', color: '#4CC9F0' },
      { name: '缓存开销', pct: '25', color: '#06D6A0' },
      { name: '其他开销', pct: '15', color: '#F72585' },
    ]),
  posX: 130,
    posY: 200,
    scale: 100,
  },
  't7-04': {
    titleText: '吞吐量随负载变化', titleSize: 54, titleColor: '#FFFFFF',
    subSize: 24, legendSize: 30, legendColor: '#FFFFFF', xLabelColor: '#E6E6E6',
    lines: JSON.stringify([
      { name: 'A模型', color: '#4CC9F0', data: '82,27,44,61,78' },
      { name: 'B模型', color: '#F72585', data: '58,39,51,66,82' },
    ]),
    xlText: '1月,2月,3月,4月,5月,6月',
  posX: 130,
    posY: 260,
    scale: 100,
  },
  't7-05': {
    titleText: '核心指标快照', upColor: '#06D6A0', downColor: '#F72585',
    titleSize: 54, titleColor: '#FFFFFF', nameSize: 36, nameColor: '#E6E6E6',
    valSize: 72, valColor: '#FFFFFF', deltaSize: 32,
    cards: JSON.stringify([
      { name: '平均延迟', val: '24ms', delta: '↓18%', dir: 'down' },
      { name: '成功率', val: '97.2%', delta: '↑2.1%', dir: 'up' },
      { name: '指标', val: '30', delta: '↑10%', dir: 'up' },
    ]),
  posX: 130,
    posY: 240,
    scale: 100,
  },
  't7-06': {
    percent: 85, labelText: '关键占比',
    trackColor: '#444852', arcColor: '#2288dd',
    numSize: 140, numColor: '#e6e8ed',
    labelSize: 48, labelColor: '#b0b4bc',
    sliderFill: '#f0f2f6', glowColor: '#88ffbb',
    radius: 320, strokeW: 36, scale: 40,
  posX: 60,
    posY: 220,
  },
};

/** 生成某组件配置的默认值对象 */
export function defaultConfig(id: string): ConfigState {
  const base = (CONFIGS[id] ?? []).reduce<ConfigState>((acc, d) => {
    acc[d.key] = d.default;
    return acc;
  }, {});
  const ov = DEFAULTS[id];
  if (ov) {
    for (const k of Object.keys(base)) {
      if (ov[k] !== undefined) base[k] = ov[k];
    }
  }
  return base;
}

const ConfigCtx = createContext<ConfigState>({});

/** 读取配置：优先取 `<组件id>::<key>`（用于复合组件定向控制子组件），
 *  其次取全局 `<key>`（直接组件），最后回退该组件默认值 */
export function useConfigKey(id: string, key: string): number | string {
  const ctx = useContext(ConfigCtx);
  const scoped = ctx[`${id}::${key}`];
  if (scoped !== undefined && scoped !== '') return scoped;
  const plain = ctx[key];
  if (plain !== undefined && plain !== '') return plain;
  return CONFIGS[id]?.find((x) => x.key === key)?.default ?? 0;
}

export const ConfigProvider = ConfigCtx.Provider;

/** 读取 list 型(数据条目)配置，返回对象数组；出错时回退空数组 */
export function useConfigList(id: string, key: string): Record<string, string>[] {
  const raw = useConfigKey(id, key);
  if (Array.isArray(raw)) return raw as unknown as Record<string, string>[];
  if (typeof raw === 'string' && raw.trim()) {
    try {
      const j = JSON.parse(raw);
      if (Array.isArray(j)) return j;
    } catch {
      /* 忽略解析错误 */
    }
  }
  return [];
}
